const ShopActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
  SHOW_PRODUCT_DETAILS_MODAL: "SHOW_PRODUCT_DETAILS_MODAL",
  HIDE_PRODUCT_DETAILS_MODAL: "HIDE_PRODUCT_DETAILS_MODAL",
};

export default ShopActionTypes;
